repos:
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
        - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-added-large-files
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: poetry run pylint /home/vikas.deep/custom_folder/my_test/git/security_sign/handler.py
          language: system
          always_run: true
          pass_filenames: false